# Default values for msockperf
namespace: sre-sockperf-server

# Image Pull Secret from CICD Pipeline
# imagePullSecret: regcred

environmentDomain: sockperf.env.domainname.com

config:

sockperfServer:
  serviceName: sockperf-server-service
  appName: sockperf-app
  image: ghcr.io/aetrius/msockperf-server/msockperf-server:main
  replicaCount: 1
  revisionHistoryLimit: 1
  sockperfPort: 3600
  webPort: 3600
