---
namespace:
  enabled: true
  name: sre-msockperf-exporter

environmentDomain: msockperf.domainname.com

labels:
  enabled: true
  owner: "sre"

ingress:
  enabled: true

portworx:
  enabled: false

rancher:
  enabled: true
  projectID: 

msockperf:
  serviceName: msockperf-service
  appName: msockperf-app
  image: ghcr.io/aetrius/msockperf-client/msockperf-client:main
  replicaCount: 1
  revisionHistoryLimit: 0
  webPort: 8082
  namespace: default
  remoteHost: sockperf-server-service.sre-msockperf-exporter
  remotePort: 3600
  servicePort: 8000
  imagePullPolicy: Always

sockperfServer:
  serviceName: sockperf-server-service
  appName: sockperf-app
  image: ghcr.io/aetrius/msockperf-server/msockperf-server:main
  replicaCount: 1
  revisionHistoryLimit: 1
  sockperfPort: 3600
  webPort: 3600
