apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: {{ .Values.sockperfServer.appName }}-ingress
  namespace: {{.Release.Namespace}}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.environmentDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.sockperfServer.serviceName }}
                port:
                  number: {{ .Values.sockperfServer.webPort }}
            path: /
            pathType: Prefix
          
