# Default values for msockperf
namespace: sre-msockperf-exporter

# Image Pull Secret from CICD Pipeline
# imagePullSecret: regcred

environmentDomain: msockperf.env.domainname.com

config:

msockperf:
  serviceName: msockperf-service
  appName: msockperf-app
  image: ghcr.io/aetrius/msockperf-server/msockperf-server:main
  replicaCount: 1
  revisionHistoryLimit: 1
  webPort: 443
  namespace: default
  remoteHost: test.svc.default
  remotePort: 11111
