# Default values for msockperf
namespace: sre-msockperf-exporter

# Image Pull Secret from CICD Pipeline
# imagePullSecret: regcred

environmentDomain: msockperf.env.domainname.com

config:

msockperf:
  serviceName: msockperf-service
  appName: msockperf-app
  image: ghcr.io/aetrius/msockperf-client/msockperf-client:main
  replicaCount: 1
  revisionHistoryLimit: 1
  webPort: 8082
  namespace: default
  remoteHost: msockperf-service.sre-msockperf-exporter
  remotePort: 443
