# --- 
{{- if .Values.namespace.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  annotations:
    {{- if .Values.rancher.enabled }}
    field.cattle.io/projectId: {{ .Values.rancher.projectID}}
    {{- end }}
  labels:
    {{- if .Values.rancher.enabled }}
    pds.portworx.com/available: "false"
    {{- end }}
    {{- if .Values.rancher.enabled }}
    owner: {{ .Values.labels.owner}}
    {{- end }}
{{- end }}
