apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sockperfServer.serviceName }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.sockperfServer.webPort }}
    targetPort: {{ .Values.sockperfServer.webPort }}
    protocol: TCP
    name: web 
  selector:
    app: {{ .Values.sockperfServer.appName }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
