name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        run: echo "${{ secrets.REPO_SECRET }}" | docker login -u "${{ github.actor }}" --password-stdin docker.pkg.github.com

      - name: Build and push Docker image
        run: |
          export COMMIT_SHA=$(git rev-parse HEAD)
          docker build -t docker.pkg.github.com/${{ github.repository }}/your-image-name:$COMMIT_SHA -f Dockerfile-ubuntu-server .
          docker push docker.pkg.github.com/${{ github.repository }}/your-image-name:$COMMIT_SHA

      - name: Cleanup
        run: docker logout docker.pkg.github.com
